# Generated by Django 5.0.1 on 2025-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=50)),
                ('quantity_in_stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='sweets/')),
                ('is_available', models.BooleanField(default=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('nutritional_info', models.JSONField(blank=True, null=True)),
                ('offer_percent', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
