# Generated by Django 5.0.1 on 2025-07-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sweet',
            old_name='price',
            new_name='price_per_kg',
        ),
        migrations.RenameField(
            model_name='sweet',
            old_name='quantity_in_stock',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='sweet',
            name='nutritional_info',
        ),
        migrations.RemoveField(
            model_name='sweet',
            name='rating',
        ),
    ]
